# Host версия контроллера
apiVersion: v1
kind: Service
metadata:
  labels:
    svc: ingress-nginx-metrics-host
  name: ingress-nginx-controller-metrics-host
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: 10254
  selector:
    app.kubernetes.io/name: ingress-nginx-host
    app.kubernetes.io/instance: ingress-nginx-host
    app.kubernetes.io/component: controller

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-metric-host
  namespace: ingress-nginx
  labels:
    svc: ingress-nginx-metrics-host
spec:
  endpoints:
  - targetPort: metrics
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      svc: ingress-nginx-metrics-host
